### ISSUE TITLE
OSError: Stephen-smj/LlamaCare does not appear to have a file named config.json. Checkout 'https://huggingface.co/Stephen-smj/LlamaCare/tree/main' for available files.

### ISSUE THREAD

**Issue by ylx-lier** [Stephen-SMJ/LLamaCare#1]
It appears that the file "config.json" is missing. When you have a moment, could you please upload it? Thank you!

**Comment by Stephen-SMJ** [comment]
Hi, all files of LLM like config.json you can find in the original hf repository of LLaMA2. I only upload files after fine-tuning. Thanks.
